# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9200fb5a621cb7fc44c84ba1d61ca15fa81a409791039677224cccffc8d1673f00c57a64ca4e06fe74a75e29e3b1597d2c2b0b2d92f4b5bf8e93244ad84e11a1

test:
  secret_key_base: e7733e7d7f6dc9a8fa79404e79580c612600e6216a897c9860af917e79fc3cc44f5d2d69b0836f5d647001eac1e53a1b20880db4db388f9c350d17a94d5d012f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
